# Домашнее задание Ⅱ

## Задача II.7.10

> Пусть $d_k>0, k=1,2,\ldots,n$. Доказать, что $\|x\|=\max{d_k|x_k|}$ есть норма $x$. Найти норму матрицы, подчиненную этой векторной норме.

Покажем, что для нее выполняются аксиомы нормы
1. $\|x\|=\max{d_k|x_k|}\ge 0$, так как $d_k>0, |x_k|\ge 0$
2. $\|x\|=0\Leftrightarrow d_k|x_k|=0\ \forall k\Leftrightarrow x_k=0\ \forall k\Leftrightarrow x=0_V$
3. $\|\alpha x\|=\max{d_k|\alpha x_k|}=|\alpha|\max{d_k|x_k|}=|\alpha|\cdot\|x\|$
4. $\|x+y\|=\max\limits_k{d_k|x_k+y_k|}\le\max\limits_k{(d_k|x_k|+d_k|y_k|)}\le\max\limits_k{(\max\limits_i{d_i|x_i|}+\max\limits_j{d_j|y_j|})}=\max\limits_i{d_i|x_i|}+\max\limits_j{d_j|y_j|}=\|x\|+\|y\|$

Подчиненная норма
$$\|A\|=\sup_{\|x\|=1}\|Ax\|=\sup_{\|x\|=1}\max_i\left(d_i\left|\sum_{j=1}^n a_{ij}x_j\right|\right)$$

$\{x:||x||=1\}=\{(x_j)_{j=1}^n:(\forall k\ |x_k|\le 1/d_k)\wedge(\exists k_0\ |x_{k_0}|=1/d_{k_0})\}$, тогда для всех $i$
$$\left|\sum_{j=1}^n a_{ij}x_j\right|\le\sum_{j=1}^n |a_{ij}| |x_j|\le\sum_{j=1}^n\frac{|a_{ij}|}{d_j}$$
и равенство достигается при $x^{(0)}=\left(\frac{\text{sgn}(a_{ij})}{d_j}\right)_{j=1}^n, \|x^{(0)}\|=1$, поэтому

$$\|A\|=\max_i\left(d_i\sum_{j=1}^n\frac{|a_{ij}|}{d_j}\right)$$

## Задача II.9.2a

> Дана система линейных алгебраических уравнений $Ax = b$ $$A=\begin{pmatrix}
101 & 110 \\
110 & 122 
\end{pmatrix};
b=\begin{pmatrix}
312 \\
342
\end{pmatrix};
\frac{\|\Delta b\|_1}{\|b\|_1}\le0.01;\|x\|_1=\max\limits_i |x_i|$$
> Оценить максимально точно относительную погрешность $\|\Delta x\|/\|x\|$ в заданной норме. Найти вектор ошибки $\Delta b$, на котором эта оценка достигается. При каком $\Delta b$  относительная ошибка $\|\Delta x\|/\|x\|$ будет минимальной? Найти ее.

Решением $Ax=b$ является $x=(2\ 1)^T$, также
$$A^{-1}=\frac{1}{|101\cdot122-110^2|}\begin{pmatrix}
122 & -110 \\
-110 & 101
\end{pmatrix}=\frac{1}{222}\begin{pmatrix}
122 & -110 \\
-110 & 101
\end{pmatrix}
$$
$$A(x+\Delta x)=b+\Delta b\Rightarrow\Delta x=A^{-1}\Delta b$$
Тогда точная верхняя оценка погрешности
$$\frac{\|\Delta x\|}{\|x\|}\le\frac{\|A^{-1}\|\|\Delta b\|}{\|x\|}=\|A^{-1}\|\frac{\|b\|}{\|x\|}\frac{\|\Delta b\|}{\|b\|}=
\frac{232}{222}\cdot\frac{342}{2}\cdot0.01=\frac{1653}{925}$$
Она достигается при $\|A^{-1}\Delta b\|=\|A^{-1}\|\|\Delta b\|$, что выполняется при $\Delta b=(-3.42\ 3.42)^T$
$$\begin{cases}
101x'_1+110x'_2=312-3.42 \\
110x'_1+122x'_2=342+3.42
\end{cases}\Leftrightarrow
x'=\begin{pmatrix}
-\frac{1456}{925} \\
\frac{15727}{3700}
\end{pmatrix}
$$
$$\frac{\|x'-x\|}{\|x\|}=\frac{1}{2}\max\left\{\frac{3306}{925},\frac{12027}{3700}\right\}=\frac{1653}{925}$$

Минимальная ошибка равна
$$\frac{\|\Delta x\|}{\|x\|}=\min\limits_{\|\Delta b\|=3.42}\frac{\|A^{-1}\Delta b\|}{\|x\|}=\frac{\|\Delta b\|}{\|A\|\|x\|}=\frac{171}{23200}$$
так как $\|A\Delta x\|=\|\Delta b\|$, то
$$\begin{cases}
|101\Delta x_1+110\Delta x_2|\le211\cdot2\frac{171}{23200}<3.42 \\
|110\Delta x_1+122\Delta x_2|\le232\cdot2\frac{171}{23200}=3.42
\end{cases}$$
равенство достигается при $\Delta x_1=\Delta x_2=\frac{171}{11600}$, откуда искомое $\Delta b=(\frac{36081}{11600}\ 3.42)^T$

## Задача II.7.37в

> Найти область сходимости метода Якоби и метода Зейделя для системы с матрицой вида:
\begin{pmatrix}
\alpha & \beta & 0 \\
\beta & \alpha & 0 \\
0 & 0 & \alpha 
\end{pmatrix}

Исключим случай вырожденности матрицы $\alpha=0$ и воспользуемся соответствующими критериями сходимости
1) Метода Якоби
$$\begin{vmatrix}
\lambda\alpha & \beta & 0 \\
\beta & \lambda\alpha & 0 \\
0 & 0 & \lambda\alpha 
\end{vmatrix}=\lambda\alpha(\lambda^2\alpha^2-\beta^2)=0\Leftrightarrow\lambda_{1,2}=\pm\frac{\beta}{\alpha}, \lambda_3=0$$
$$|\lambda_i|\le 1, i=1,2,3\Leftrightarrow |\beta|\le|\alpha|$$
2) Метода Зейделя
$$\begin{vmatrix}
\lambda\alpha & \beta & 0 \\
\lambda\beta & \lambda\alpha & 0 \\
0 & 0 & \lambda\alpha 
\end{vmatrix}=\lambda^2\alpha(\lambda\alpha^2-\beta^2)=0\Leftrightarrow\lambda_{1,2}=0, \lambda_3=\frac{\beta^2}{\alpha^2}$$
$$|\lambda_i|\le 1, i=1,2,3\Leftrightarrow |\beta|\le|\alpha|$$

Ответ: оба метода сходятся при $\alpha\neq 0, |\alpha|\ge|\beta|$



## Задача 2*б

> Реализуйте метод Гаусса-Зейделя решения системы уравнений
\begin{cases}
x_1 + x_2 + x_3 + \cdots + x_{99} + x_{100} &= 100 \\
x_1 + 10x_2 + x_3 &= 99 \\
\qquad \ x_2 + 10x_3 + x_4 &= 98 \\
\qquad \qquad \quad \quad \ \ddots \\
\qquad \qquad \quad \ \ x_{98} + 10x_{99} + x_{100} &= 2 \\
\qquad \qquad \qquad \qquad \quad x_{99} + x_{100} &= 1
\end{cases}
При помощи степенного метода оцените число обусловенности матрицы системы. Используя оценку числа обусловенности, получить решение системы с относительной точностью $\varepsilon=10^{−5}$

Введем параметры СЛАУ: размерность $n$, матрица $A=(a_{ij})_{i,j=1}^n$, вектор значений $b=(b_1, \ldots, b_n)^T$

In [2]:
import numpy as np

n = 100
a = np.diag(10 * np.ones(n)) + np.diag(np.ones(n - 1), 1) + np.diag(np.ones(n - 1), -1)
a[0] = np.ones(n)
a[n - 1][n - 1] = 1
b = np.arange(100, 0, -1)
eps = 1e-5

print(a, b, sep='\n')

[[ 1.  1.  1. ...  1.  1.  1.]
 [ 1. 10.  1. ...  0.  0.  0.]
 [ 0.  1. 10. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... 10.  1.  0.]
 [ 0.  0.  0. ...  1. 10.  1.]
 [ 0.  0.  0. ...  0.  1.  1.]]
[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10   9   8   7   6   5   4   3   2   1]


Найдем число обусловленности матрицы $A$ по евклидовой норме
$$\mu(A)=\sqrt{\frac{\lambda_{\max{|\cdot|}}(A^T A)}{\lambda_{\min{|\cdot|}}(A^T A)}}$$
Для этого с помощью степенного метода найдем максимальное по модулю собственное значение
$$\lambda_1=\lambda_{\max{|\cdot|}}(A^T A)$$
Затем минимальное из соотношения
$$\lambda_{\max{|\cdot|}}(\lambda_1 E - A^T A)=\lambda_1-\lambda_n$$

In [3]:
def lambda_max_abs(a):
    x = np.ones(n)
    m = 0
    while True:
        x_ = a @ x
        m_ = np.dot(x_, x) / np.dot(x, x)
        if np.abs(m - m_) <= eps:
            break
        x = x_ / np.linalg.norm(x_)
        m = m_
    return m

def lambda_min_abs(a):
    lam_max_abs = lambda_max_abs(a)
    return lam_max_abs - lambda_max_abs(lam_max_abs * np.eye(n) - a)

def cond(a):
    a = a.T @ a
    return np.sqrt(lambda_max_abs(a) / lambda_min_abs(a))

print(cond(a), np.linalg.cond(a), sep='\t')

30.709329615580604	30.768233436976338


Метод Гаусса-Зейделя дает следующее соотношение между итерациями $x$
$$x_i^{(k+1)}=\sum_{j=1}^{i-1}c_{ij}x_j^{(k+1)}+c_{ii}x_i^{(k)}+\sum_{j=i+1}^{n}c_{ij}x_j^{(k)}+d_i
\text{, where }c_{ij}=\begin{cases}
0, & \text{if }i=j \\
-a_{ij} / a_{ii}, & \text{if }i\neq j
\end{cases}, d_i = \frac{b_i}{a_{ii}}, i=1,2,\ldots,n$$
Программная реализация с условием остановки $$\mu(A)\frac{\|r_k\|}{\|b\|}\le\varepsilon$$

In [16]:
c = a / a.diagonal()[:, None]
d = b / a.diagonal()
np.fill_diagonal(c, 0)

threshold = eps * np.linalg.norm(b) / cond(a)
x = np.ones(n)

while np.linalg.norm(a @ x - b) > threshold:
    for i in range(n):
        x[i] = d[i] - c[i] @ x

x0 = np.linalg.solve(a, b)
rx = np.linalg.norm(x-x0, 2) / np.linalg.norm(x0, 2)

with np.printoptions(precision=6, suppress=True):
    print('Approximate solution\n', x)
    print('Accurate solution\n', x0)
    print(f'Relative variance {rx} <= eps = {eps}')

Approximate solution
 [-345.745015   44.019177    4.553246    8.448363    7.963124    7.920392
    7.832957    7.750038    7.666663    7.583334    7.5         7.416667
    7.333333    7.25        7.166667    7.083333    7.          6.916667
    6.833333    6.75        6.666667    6.583333    6.5         6.416667
    6.333333    6.25        6.166667    6.083333    6.          5.916667
    5.833333    5.75        5.666667    5.583333    5.5         5.416667
    5.333333    5.25        5.166667    5.083333    5.          4.916667
    4.833333    4.75        4.666667    4.583333    4.5         4.416667
    4.333333    4.25        4.166667    4.083333    4.          3.916667
    3.833333    3.75        3.666667    3.583333    3.5         3.416667
    3.333333    3.25        3.166667    3.083333    3.          2.916667
    2.833333    2.75        2.666667    2.583333    2.5         2.416667
    2.333333    2.25        2.166667    2.083333    2.          1.916667
    1.833333    1.75        1